[build]
buildCommand = "npm ci && npm run build -w client && npm run build -w backend"

[deploy]
preDeployCommand = "npm run migrate -w backend"
startCommand = "npm run start -w backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
