[build]
buildCommand = "pnpm install --frozen-lockfile && pnpm --filter backend build"

[deploy]
preDeployCommand = "pnpm --filter backend run migrate && pnpm --filter backend deploy-commands"
startCommand = "pnpm --filter backend start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
